/**
 * Disk I/O for the locale artifacts — the thin fs layer around the pure
 * (de)serialization in `./locale`. Each locale is two files under
 * `clean-jsdoc-theme-artifacts/locales/` (the plan, §5):
 *
 *  - `<code>.json` — the **editable** translations (`_version`/`chrome`/`api`).
 *  - `<code>.meta.json` — the **auto-managed** `_hashes`/`_obsolete` the user
 *    never touches (pure processing state for staleness + soft-delete).
 *
 * Splitting them keeps the file a translator edits free of machine bookkeeping.
 */

import { mkdir, readFile, readdir, unlink, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import {
  parseLocaleFiles,
  serializeLocaleContent,
  serializeLocaleMeta,
  type LocaleFile,
} from './locale';

/** Default artifacts directory, relative to the project root (the config's cwd). */
export const DEFAULT_ARTIFACTS_DIR = 'clean-jsdoc-theme-artifacts/locales';

/** Absolute path of the editable locale file within `dir`. */
export function localeFilePath(dir: string, code: string): string {
  return join(resolve(dir), `${code}.json`);
}

/** Absolute path of the auto-managed meta sidecar within `dir`. */
export function localeMetaFilePath(dir: string, code: string): string {
  return join(resolve(dir), `${code}.meta.json`);
}

/** Read a file, returning `null` on ENOENT (rethrowing anything else). */
async function readOrNull(path: string): Promise<string | null> {
  try {
    return await readFile(path, 'utf8');
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === 'ENOENT') return null;
    throw err;
  }
}

/**
 * Read + recombine a locale's content + meta files, or `null` when the editable
 * file doesn't exist yet (first run). A present content file with a missing meta
 * sidecar recombines with empty hashes/obsolete (self-heals on next extract).
 */
export async function readLocaleFile(dir: string, code: string): Promise<LocaleFile | null> {
  const content = await readOrNull(localeFilePath(dir, code));
  if (content === null) return null;
  const meta = await readOrNull(localeMetaFilePath(dir, code));
  return parseLocaleFiles(content, meta);
}

/** Serialize + write a locale's content + meta files (creating the dir if needed). */
export async function writeLocaleFile(dir: string, code: string, file: LocaleFile): Promise<void> {
  await mkdir(resolve(dir), { recursive: true });
  await writeFile(localeFilePath(dir, code), serializeLocaleContent(file), 'utf8');
  await writeFile(localeMetaFilePath(dir, code), serializeLocaleMeta(file), 'utf8');
}

/** Subdirectory (under the artifacts dir) holding the generated `prompt` files. */
export const PROMPTS_SUBDIR = 'prompts';

/** Absolute path of the prompts directory within `dir`. */
export function promptsDirPath(dir: string): string {
  return join(resolve(dir), PROMPTS_SUBDIR);
}

/** Escape a string for safe interpolation into a `RegExp`. */
function escapeRegExp(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/** The file name for a locale's prompt chunk (single chunk → `<code>.md`). */
function promptFileName(code: string, index: number, total: number): string {
  if (total <= 1) return `${code}.md`;
  return `${code}.part-${String(index + 1).padStart(2, '0')}.md`;
}

/** Remove any prompt files belonging to `code` so a re-run never leaves stale parts. */
async function removeLocalePromptFiles(promptsDir: string, code: string): Promise<void> {
  let names: string[];
  try {
    names = await readdir(promptsDir);
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === 'ENOENT') return;
    throw err;
  }
  const single = `${code}.md`;
  const part = new RegExp(`^${escapeRegExp(code)}\\.part-\\d+\\.md$`);
  await Promise.all(
    names.filter((n) => n === single || part.test(n)).map((n) => unlink(join(promptsDir, n)))
  );
}

/**
 * Write a locale's prompt chunks as Markdown files under `<dir>/prompts/`, one
 * file per chunk (a single chunk → `<code>.md`; many → `<code>.part-NN.md`),
 * so the user can copy/paste or upload the file straight to an LLM instead of
 * scraping it out of the console. Stale prompt files for the same locale from a
 * previous run are removed first, so a shrinking translation set never leaves
 * orphaned parts behind. Returns the absolute paths written, in chunk order.
 */
export async function writePromptFiles(
  dir: string,
  code: string,
  chunks: string[]
): Promise<string[]> {
  const promptsDir = promptsDirPath(dir);
  await mkdir(promptsDir, { recursive: true });
  // The prompts are transient (regenerated every run from the committed catalogs),
  // so keep the whole directory out of version control without the user configuring
  // anything. `*` ignores the .gitignore itself too, so nothing here is committed.
  await writeFile(
    join(promptsDir, '.gitignore'),
    '# Transient translation prompts — regenerated by `clean-jsdoc prompt`. Safe to delete.\n*\n',
    'utf8'
  );
  await removeLocalePromptFiles(promptsDir, code);
  const paths: string[] = [];
  for (let i = 0; i < chunks.length; i++) {
    const path = join(promptsDir, promptFileName(code, i, chunks.length));
    const body = chunks[i].endsWith('\n') ? chunks[i] : `${chunks[i]}\n`;
    await writeFile(path, body, 'utf8');
    paths.push(path);
  }
  return paths;
}
