/*
 * Compiles dwar's static Tailwind utility layer ONCE (at dwar's own build time)
 * and codegens it into src/generated/utility-css.ts as an inlined string.
 *
 * Why codegen-to-string instead of shipping a .css file dwar reads at runtime:
 * `render()` is pure (no fs). Inlining the utilities as a module constant keeps
 * that guarantee while still using real Tailwind. The dynamic theme-token block
 * (`:root { --clean-* }`) is produced separately at render time in src/css.ts.
 *
 * Tailwind is invoked via its CLI in a child process (not the programmatic Node
 * API), which is the stable surface across v4 point releases.
 */

import { execFileSync } from 'node:child_process';
import { createRequire } from 'node:module';
import { readFileSync, writeFileSync, mkdirSync, rmSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const here = dirname(fileURLToPath(import.meta.url));
const pkgDir = join(here, '..');

// The CLI's `exports` map doesn't expose the bin as a subpath, so resolve it
// relative to the package.json (its `bin` field points at ./dist/index.mjs).
const cliPkgJson = require.resolve('@tailwindcss/cli/package.json');
const cliBin = require(cliPkgJson).bin.tailwindcss;
const cliEntry = join(dirname(cliPkgJson), cliBin);
const input = join(pkgDir, 'styles', 'tailwind.css');
const tmpOut = join(pkgDir, 'styles', '.utilities.generated.css');
const genTs = join(pkgDir, 'src', 'generated', 'utility-css.ts');

execFileSync(process.execPath, [cliEntry, '-i', input, '-o', tmpOut, '--minify'], {
  stdio: 'inherit',
  cwd: pkgDir,
});

const css = readFileSync(tmpOut, 'utf8').trim();
rmSync(tmpOut, { force: true });

mkdirSync(dirname(genTs), { recursive: true });
const banner =
  '/* AUTO-GENERATED by scripts/build-css.mjs — do not edit by hand. */\n' +
  '/* eslint-disable */\n';
writeFileSync(genTs, `${banner}export const UTILITY_CSS = ${JSON.stringify(css)};\n`);

console.log(`[build-css] wrote ${css.length} bytes → src/generated/utility-css.ts`);
